Testing Page HTML and CSS Layout
Jforjo/CSD pull request #5
Opened 2024-02-19 15:34 UTC by chrisn02

Have created the HTML and CSS layout for the testing page. The subject and test names are displayed in the top corner of the screen. There is space for the question to go with the question number as well as a progress bar underneath it. The answer boxes increase in size slightly when hovered over and while it has not been implemented yet I am planning on having it so that when you click on an answer a button will appear on the bottom right corner of the page to advance to the next question. As seen in the image there is some blank space but this was not there when I was originally making the page, so will have to adjust based on screen size.
![TestingPage](https://github.com/Jforjo/CSD/assets/59711723/9483e7f8-8999-4806-ae08-cac1b0564f1d)

2024-02-19 15:36 UTC, gchodancar19 approved these changes
Is there anything else to added like coding.

2024-02-20 08:52 UTC, Jforjo requested changes
See individual comments.

2024-02-20 08:52 UTC, Jforjo commented on style.css
> +        height: 20%;
The answers box should also be taller, as I think each box is too small in height right now.

2024-02-20 08:52 UTC, Jforjo commented on style.css
> +        grid-template-columns: 1fr 1fr;
When the screen gets too small you should just use 1 column so the questions stack on top of each other.

2024-02-20 08:52 UTC, Jforjo commented on style.css
> +        min-height: 100px;
There is no need to have both `max-height` and `min-height` - just use `height`.

2024-02-20 08:52 UTC, Jforjo commented on style.css
> +        min-width: 900px;
This `min-width` will cause the question to spill off the screen when the view-width gets too small. You can just remove this.

2024-02-20 08:52 UTC, Jforjo commented on style.css
> +        margin-bottom: 20px;
This is redundant as you have `margin: 0 auto;` below, which overwrites this `margin-bottom`.

2024-02-20 13:03 UTC, chrisn02 commented
Thanks for your feedback, I will work on this now.

2024-02-20 13:41 UTC, chrisn02 commented
Have made the requested changes. Have made the answer boxes taller and when on a smaller screen such as mobile, the boxes will stack on top of each other. The progress bar now fills based on percentage, the image is on 75% as an example. Let me you what you think.
![TestingPage_Fix](https://github.com/Jforjo/CSD/assets/59711723/5baf1f38-2448-455e-9c78-7b3df982bb0c)
![TestingPage_MobileView](https://github.com/Jforjo/CSD/assets/59711723/cef33ced-13d4-4924-aecd-f9943173b71d)

2024-02-20 14:38 UTC, Jforjo approved these changes
Looks good, but should should also make sure it looks good if there are only 2 or 3 answers too.

2024-02-20 14:58 UTC, Jforjo approved these changes
I don't think you can merge something if you've also made changes, since we have to approve it again. You've added a new line with nothing on it, which is a change that we need to review. When merging make sure there are no changes next time.

2024-02-20 15:06 UTC, chrisn02 commented
I think that must've happened as I was resolving a merge conflict, apologies

2024-02-20 15:06 UTC, merged