CN Stats Page HTML & CSS Layout
Jforjo/CSD pull request #6
Opened 2024-03-04 14:57 UTC by chrisn02

Have made the layout for the user stats page. At the top of the page it says "Stats for [name]" with a graph underneath that shows the percentage of every quiz the user has done, and you can hover over each point in the graph to see the exact percentage. Underneath that is a table that shows data about each individual test. Table may need to some changes but the basic layout is there. It also displays the average score of each test as well as the total number of points earned. There are plans for an export functionality as well, which will be implemented at a later date.
![UserStatsPageLayout](https://github.com/Jforjo/CSD/assets/59711723/fc1179fd-d417-4cf8-9ad7-91ffb2bc7772)
![UserStatsPageLayout_Hovered](https://github.com/Jforjo/CSD/assets/59711723/57d5371a-538f-4c8b-ba76-ca4548565eda)

2024-03-04 15:27 UTC, Jforjo requested changes
Looks good. Read comments.
__Could__ change the line graph to have it's maximum and minimum values being the highest and lowest scores respectively. This is because if someone keeps scoring between 70% and 80% then it would be hard to see the change, so removing the redundant space above and below would emphasis the users progress more.

2024-03-04 15:27 UTC, Jforjo commented on style.css
> +        margin: 0 auto;
Try not to have a margin on the body. You should use things like `display: flex;`, `justify-content: center;` and `flex-direction: center;`.

2024-03-04 15:27 UTC, Jforjo commented on user-stats.php
> +    <section class="welcome-section">
I don't think a section tag should be used here. The `<h2>` inside should wither be within the header, as that would logically make sense, or as it is right now.

2024-03-04 15:27 UTC, Jforjo commented on user-stats.php
> +    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
Move this into the `<head>` tag at the top and add the defer attribute to it.
It should look like this: `<script defer src="...">`.
This is how all script files should be.

2024-03-04 15:27 UTC, Jforjo commented on user-stats.php
> +    <script>
You should probably put this within an external script file.

2024-03-04 15:35 UTC, gchodancar19 approved these changes
As you are using bootstrap there are some stuff which not needed specially the utility stuff is not necessarily needed.

2024-03-06 19:16 UTC, Jforjo commented on user-stats.php
> +    <link defer href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJ
The defer attribute is specific to script tags, so you can remove it from this link tag.

2024-03-06 19:18 UTC, chrisn02 commented on user-stats.php
> +    <link defer href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJ
Didn't mean to add that, thanks for letting me know

2024-03-06 19:18 UTC, chrisn02 commented
Have made the requested changes. The graph now displays from the user's lowest score to their highest score by changing beginAtZero from true to false, and have also moved the javascript code for the graph into its own file called graph.js
![image](https://github.com/Jforjo/CSD/assets/59711723/278b09a9-c8ec-478b-9148-52fc9a620558)

2024-03-06 19:32 UTC, Jforjo approved these changes
Front-end looks good.
Although, I would suggest putting all your JavaScript inside an anonymous function, like this:
```javascript
(() => {
    // code...
})();
```
but this isn't necessary.

2024-03-06 19:34 UTC, chrisn02 commented
Thanks, will look into doing that

2024-03-08 11:23 UTC, chrisn02 commented
Sorry, resolved a merge conflict so requires review again

2024-03-08 12:34 UTC, Jforjo approved these changes

2024-03-08 12:47 UTC, merged